server:
  port: 8081

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: wangsen
    password: 123456
    listener:
      simple:
        prefetch: 1  #预读取数量，每次只能获取一条消息，处理完才能获取下一个消息
