# 配置redis连接
spring:
  redis:
    host: localhost
    port: 6379
    client-type: Jedis

  datasource:
    url: jdbc:mysql://101.42.176.44:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 169167866Spl.
    driver-class-name: com.mysql.cj.jdbc.Driver


