spring:
#  配置数据源，连接数据库
  datasource:
    url: jdbc:mysql://101.42.176.44:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 169167866Spl.
    driver-class-name: com.mysql.cj.jdbc.Driver
#    配置spring自带定时任务
  task:
    scheduling:
      thread-name-prefix: spring_tasks_ #配置定时任务线程前缀名
      pool:
        size: 2   #配置定时任务线程池大小
      shutdown:
        await-termination: false  #线程关闭时等待所有任务完成
        await-termination-period: 5s #调度线程关闭前最大等待时间，确保最后一定关闭

  #发送邮件配置
  mail:
    host: smtp.qq.com #配置是smtp服务器地址
    port: 587 #smtp服务器端口
    username: 1376474892@qq.com #配置邮箱用户名
    password: zpnxatcbpxerjhjf #配置申请到的授权码
    default-encoding: UTF-8 #配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory #配饰ssl加密工厂
        debug: true
    from: 1376474892@qq.com #发送方邮件，配在yml中方便更改


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

